# This is quick action to build apk and share it with artifacts
# It's for convenience and nightly-testing with people
name: Build apk

on:
  workflow_dispatch:

env:
  flutter_channel: "any"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout
      
      - name: Parse fvm to set flutter version
        run: echo "flutter_version=$(cat .fvm/fvm_config.json | jq -r .flutterSdkVersion)" >> $GITHUB_ENV
      
      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-${{ env.flutter_channel }}
          restore-keys: |
            ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}-
            ${{ runner.OS }}-flutter-install-cache-
      
      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.OS }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pub-
      
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.OS }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: ${{ env.flutter_channel }}
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build apk
        run: flutter build apk --target-platform android-arm64 --release
      
      - name: Rename apk
        run: mv ./build/app/outputs/flutter-apk/app-release.apk ./freebuddy-nightly.apk
      
      - name: Upload apk as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freebuddy-nightly
          path: ./freebuddy-nightly.apk
          if-no-files-found: error
